### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by Archer6621** [Archer6621/gms-holiday-jam#1]
**Shaders**
- [x] Bloom shader
- [ ] Motion blur shader
- [ ] Create post-processing shader for background layers
- [ ] Line up supernova shader transitions better
- [ ] Lens-flare effect
- [ ] PBR? Could look sick

**Graphics**
- [ ] Implement screenshake
- [ ] Make transitions between environment layers more interesting, by making them position-based instead of just a fade (could create low-density tiles)
- [ ] Make normal maps more influential/apparent on the environment layers
- [ ] Implement starfields

**Mechanics**
- [ ] Revise spawning system
- [ ] Improve difficulty system, by allowing more params to be user-controlled (e.g. spawn density)
- [ ] Spawn objects with initial velocity

**Code Architecture**
- [ ] Remove global variables as much as possible
- [ ] Improve inheritance structuring for projectiles
- [ ] Introduce environment layer groups that can easily be linked to spawn volumes
- [ ] Improve UI system architecture (e.g. button/toggle should inherit from the same parent)

**Assets**
- [ ] Replace sprites with high quality artwork

**Fixes**
- [ ] Add announcement cancelling/staleness condition feature
- [ ] Give sound priority to music and announcer voices
- [ ] Improve environment layer system performance
- [ ] Reduce collision system glitching and improve its performance
